---
title: "ECME"
author: "Ivan"
date: "2017年5月23日"
output: html_document
---

# Function Definition
```{r}
Plot_beta0 <- function(temp)
{
    k <- ncol(temp)
    par(mfrow = c(floor(sqrt(k)),ceiling(sqrt(k))))
    lapply(1:k,function(local) plot(x = 1:nrow(temp),y = temp[,local],type = "l",
                                    xlab = "Value",ylab = colnames(temp)[local]))
}

Plot_beta0_One <- function(local,temp)
{
    plot(x = 1:nrow(temp),y = temp[,local],type = "l",
                                    xlab = "Value",ylab = colnames(temp)[local])
}

Predict <- function(x,beta0)
{
    n <- nrow(x)
    if(class(x) != "matrix")
    {
        x <- as.matrix(x,ncol = (nrow(beta0) - 1))
    }
    x <- cbind(rep(1,n),x)
    # colnames(x)[1] <- "intercept"
    pre <- x %*% beta0
    return(pre)
}

ECME_SVM <- function(x,y,alpha = 1,mu = 0.1,amu = 0.1,bmu = 0.1,iter = 100)
{
    ############################## Pre Dealing
    k <- ncol(x) # The number of the variables                               
    n <- nrow(x) # The number of the samples  
    if(class(x) != "matrix")
    {
        x <- as.matrix(x, ncol = k)
    }
    # Change the label into {-1,1};the second type is -1
    y_num <- matrix(rep(1, length(y)), ncol = 1)
    y_num[which(levels(y)[2] == y),] <- -1
    # Initialize
    sigma_lower <- c(1, apply(x, 2, sd)) # The first elements is interception
    names(sigma_lower)[1] <- "intercept"
    sigma_upper <- diag(sigma_lower^2)
    
    x <- cbind(rep(1,n),x) # Add the intercept
    tryCatch({colnames(x)[1] <- "intercept"},error = function(e){
        colnames(x) <<- c("intercept",paste("x",1:k,sep = ""))
    })
    
    
    set.seed(1) # Initialize beta0 
    beta0 <- matrix(runif(k + 1,0,1),ncol = 1) # The first element is the intercept
    
    temp <- matrix(nrow = iter,ncol = k + 1) # Temporary variables
    colnames(temp) <- colnames(x)
    
    ##############################Iterations
    omega_lower_inv <- vector(length = k)
    for(step in 1:iter)
    {
        #print(paste("Step: ",step,sep = ""))
        ##### E-Step
        lambda_lower_inv <- array(1/abs(1 - (x %*% beta0) * y_num))
        
        lambda_upper_inv <- diag(lambda_lower_inv) # lambda_upper_inv
        
        for(j in 1:(k + 1)) # omega_lower_inv
        {
            if(alpha < 2)
            {
                if(beta0[j] != 0)
                {
                    omega_lower_inv[j] <- alpha * (abs(beta0[j]) ** (alpha - 2)) * ((mu * sigma_lower[j]) ** (2 - alpha))
                }else
                {
                    omega_lower_inv[j] <- 99999
                }
            }else if(alpha == 2)
            {
                omega_lower_inv[j] <- 1
            }
        }
        
        omega_upper_inv <- diag(omega_lower_inv) # omega_upper_inv
        
        ##### M-Step
        e <- tryCatch(temp1 <- ginv(sigma_upper), error = function(e){
            sigma_upper[which(sigma_upper == Inf,arr.ind = TRUE)] = 99999
            sigma_upper[which(sigma_upper == -Inf,arr.ind = TRUE)] = -99999
            sigma_upper[which(is.na(sigma_upper),arr.ind = TRUE)] = 0.00001
            temp1 <<- ginv(sigma_upper)
        })
        
        temp2 <- (mu**(-2)) * temp1 %*% omega_upper_inv + t(x) %*% lambda_upper_inv %*% x
        
        e <- tryCatch(temp3 <- ginv(temp2), error = function(e){
            temp2[which(temp2 == Inf,arr.ind = TRUE)] <- 99999
            temp2[which(temp2 == -Inf,arr.ind = TRUE)] <- -99999
            temp2[which(is.na(temp2),arr.ind = TRUE)] <- 0.00001
            temp3 <<- ginv(temp2)
        })
        
        beta0 <- temp3 %*% t(x) %*% (matrix(rep(1,n),ncol = 1) + matrix(lambda_lower_inv,ncol = 1)) 
        
        ##### CME-Step
        mu_inv_alpha <- (bmu + sum((abs(beta0 / sigma_lower)) ** alpha)) / (k / alpha + amu - 1)
        mu <- mu_inv_alpha ** (- 1 / alpha)
        
        ##### Record
        temp[step,] <- beta0
    }
    res <- list(beta0,temp)
    return(res)
}
```

#Simulation data via e1071
```{r}
##################Simulation examples
library(MASS)
library(e1071)
set.seed(8)
x31 <- mvrnorm(250,c(10,10),matrix(c(1,0,0,1),ncol = 2))
set.seed(7)
x32 <- mvrnorm(250,c(-10,-10),matrix(c(1,0,0,1),ncol = 2))
x3 <- rbind(x32,x31)
be <- matrix(c(1,1),ncol = 1)
y3 <- factor(sign(x3 %*% be + 2),levels = c(1,-1),labels = c("P","N"))
### svm
sv <- svm(x3,y3,kernel = "linear")
summary(sv)
### Predict
pred <- predict(sv,x3)
table(pred,y3)
sum(pred == y3)/length(y3)
```

#Simulation
```{r}
res <- ECME_SVM(x3,y3,alpha = 2,mu = 0.01,amu = 0.1,bmu = 0.1,iter = 1000)
decision <- Predict(x3,res[[1]])
label <- sign(decision)
label[which(label == -1)] <- levels(y3)[2]
label[which(label == 1)] <- levels(y3)[1]
table(label,y3)
sum(label == y3)/nrow(x3)
Plot_beta0(res[[2]])
```

# Iris data via e1071
```{r}
##################Iris examplesstr(iris)
library(e1071)
x1 <- iris[which(iris[,5] %in% c("setosa","versicolor")),1:4]
y1 <- iris[which(iris[,5] %in% c("setosa","versicolor")),5]
y1 <- factor(y1) 
# svm
sv <- svm(x1,y1,kernel = "linear")
summary(sv)
### Predict
pred <- predict(sv,x1)
table(pred,y1)
sum(pred == y1)/length(y1)

```

#Iris data
```{r}
res2 <- ECME_SVM(x1,y1,alpha = 2,mu = 0.01,amu = 0.1,bmu = 0.1,iter = 1000)
decision <- Predict(x1,res2[[1]])
label <- sign(decision)
label[which(label == -1)] <- levels(y1)[2]
label[which(label == 1)] <- levels(y1)[1]
table(label,y1)
sum(label == y1)/nrow(x1)
Plot_beta0(res2[[2]])

```


