---
title: "Face"
author: "Ivan"
date: "2017年3月28日"
output: html_document
---

####Path Setting and read the data
```{r}
dir_path <- "F:/git/trial/R/Pre/Face_Recognition"
```

```{r}
if(!require(bmp))install.packages("bmp")
require(bmp)
read_bmp <- function(dir_path,i)
{
    file_name <- paste(dir_path,"/face",'/f',i,'.bmp',sep="")
    res <- read.bmp(file_name)
    return(res[,,1])
}
#translated each picture into a stacked vector of length r = 77, 760
face_data <- t(sapply(1:11, read_bmp,dir_path=dir_path))
dim(face_data)
```
#Center the data by columns
```{r}
if(!require(pixmap))install.packages("pixmap")
require(pixmap)
m <- colMeans(face_data)
#Plot the mean data
pr=pixmapRGB(matrix(m,nrow=243),ncol=320)
plot(pr)
```

#Center the data by columns
```{r}
face_data_ss <- t(apply(face_data,1,function(x)return(x-m)))
```
#Calculate the correlation 
```{r}
A <- face_data_ss%*%t(face_data_ss)
```
#Calculate the eigenvalues and eigenvectors
```{r}
eigen_value <- eigen(A)
```
#Plot the pca components plot and add one more components each plot
```{r}
par(mfrow=c(3,4))
xnew <- m

for(i in 1:11)
{
    v <- t(face_data_ss)%*%eigen_value$vector[,i]/sqrt(abs(eigen_value$values[i]))
    b <- t(v)%*%face_data_ss[2,]
    xnew <- xnew+v%*%b
    pr <- pixmapRGB(matrix(xnew,nrow=243,ncol=320))
    plot(pr)
}
```

```{r}
xnew <- m

for(i in 1:11)
{
    v <- t(face_data_ss)%*%eigen_value$vector[,i]/sqrt(abs(eigen_value$values[i]))
    b <- t(v)%*%face_data_ss[2,]
    xnew <- xnew+v%*%b
    pr <- pixmapRGB(matrix(xnew,nrow=243,ncol=320))
    plot(pr)
}
```


