---
title: "Food"
author: "Ivan"
date: "2017年3月28日"
output: html_document
---
####Path Setting
```{r}
dir_path <- "F:/git/trial/R/Pre/The_Nutritional_of_food"
raw_data <- read.table(paste(dir_path,"/food.data.txt",sep=""),header = TRUE,stringsAsFactors = FALSE)
```
####Only use the first seven columns
```{r}
use_data <- raw_data[,1:7]
```
####Chenk the structure of the data
```{r}
dim(use_data)
str(use_data)
```
####Plot density graphs
```{r}
#Preparation
if(!require(ggplot2))install.packages("ggplot2")
if(!require(reshape))install.packages("reshape")
require(ggplot2)
require(reshape)
#Transform the format of data to plot
Plot_Density <- function(use_data,xtart=0,xend=10,ystart=0,yend=1)
{
    id <- 1:nrow(use_data)
    long_data <- cbind(use_data,id)
    long_data <- melt(long_data,id="id")
    ggplot(long_data,aes(x=value,colour=variable))+geom_density()+
        xlim(0,xend)+ylim(0,yend)
}

Plot_A_Density <- function(name,use_data)
{
    use <- use_data[,name]
    plot(density(use),xlab=name,main="density line")
}

```
####Check density plots of all variables
```{r}
Plot_Density(use_data,xend=50)
lapply(colnames(use_data),Plot_A_Density,use_data=use_data)
```
####Chenk distribution of all variables
```{r}
if(!require(Hmisc))install.packages("Hmisc")
require(Hmisc)
describe(use_data)
```
####Check the missing values
```{r}
if(!require(mice))install.packages("mice")
require(mice)
md.pattern(use_data)
```
####PCA preparation
```{r}
div <- function(x,y) return(x/y)
#divide variable of wight.grams
use_data_div <- apply(use_data,2,div,y=use_data[,"weight.grams"])
```
####PCA
```{r}
#remove variable of wight.grams
use_data_div <- use_data_div[,-which("weight.grams"==colnames(use_data_div))]
#Standardlize
use_data_div_ss <- scale(use_data_div)
#PCA
result <- princomp(use_data_div_ss)
```
####The result of PCA
```{r}
summary(result)
head(result$loadings)
head(result$scores)
```
####Scree plot
```{r}
plot(result,type="l")
```



